[workspace]
members = [
  "client",
  "cli",
  "dev",
  "examples/oai-actix"
]
default-members = ["dev"]
[package]
name = "oai"
version = "0.1.0"
edition = "2021"

[lib]
name = "client"
path = "client/src/lib.rs"

[[bin]]
name = "cli"
path = "cli/src/bin.rs"

[[bin]]
name = "dev"
path = "dev/src/main.rs"


[[bin]]
name = "oai-actix"
path = "examples/oai-actix/src/main.rs"