[workspace]
members = [
  "client",
  "cli",
  "sandbox",
]
default-members = ["sandbox"]
[package]
name = "oai"
version = "0.1.0"
edition = "2021"

[lib]
name = "client"
path = "client/src/lib.rs"

[[bin]]
name = "cli"
path = "cli/src/bin.rs"

[[bin]]
name = "sandbox"
path = "sandbox/src/main.rs"