[workspace]
members = [
  "client",
  "cli",
  "playground",
]
default-members = ["dev"]
[package]
name = "oai"
version = "0.1.0"
edition = "2021"

[lib]
name = "client"
path = "client/src/lib.rs"

[[bin]]
name = "cli"
path = "cli/src/bin.rs"

[[bin]]
name = "playground"
path = "playground/src/main.rs"