on: [push, pull_request]

name: CI Checklist

jobs:
  fmt:
    name: is formated?
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add rustfmt
        run: rustup component add rustfmt
      - name: Run rusfmt check
        run: cargo fmt --all -- --check

  clippy:
    name: is linted?
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add clippy
        run: rustup component add clippy
      - name: Run clippy Check
        run: cargo clippy -- -D warnings

  check:
    name: cargo check passing?
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run check
      run: cargo check --verbose

  test:
    name: tests passing?
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose

  build:
    name: release builds?
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run build
      run: cargo build --release --verbose

