name: Rust

on:
  push:
    branches: [ "main, candidate, develop" ]
  pull_request:
    branches: [ "main, candidate, develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Checkout submodules
    - uses: textbook/git-checkout-submodule-action@master
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
