on: [push, pull_request]

name: Continuous integration

jobs:
  fmt:
    name: Formated
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add rustfmt
        run: rustup component add rustfmt
      - name: Run rusfmt check
        run: cargo fmt --all -- --check

  clippy:
    name: Linted
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add clippy
        run: rustup component add clippy
      - name: Run clippy Check
        run: cargo clippy -- -D warnings

  check:
    name: Checked
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run check
      run: cargo check --verbose

  test:
    name: Tested
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose

  build:
    name: Released
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run build
      run: cargo build --release --verbose

